[env:esp32dev]
platform = espressif32@^6        ; dùng bản platform mới (Arduino-ESP32 2.x)
board = esp32dev
framework = arduino

; tùy chọn nhưng nên có để dùng LittleFS làm FS mặc định
board_build.filesystem = littlefs

lib_deps =
    mikalhart/TinyGPSPlus
    mobizt/Firebase ESP32 Client
    jrowberg/I2Cdevlib-MPU6050

monitor_speed = 115200
upload_speed  = 921600
