[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_ldf_mode = deep+

build_flags =
    -I lib/cArithmeticMacro
    -I lib/cBitWiseMacro
    -I lib/cLoopMacro
    -I lib/cReturnType
    -I lib/espSerialWrap
    -I lib/freeRTOSWrap
    -I lib/HCSR04Wrap
    -I lib/MPU6050Wrap

lib_deps =
    mikalhart/TinyGPSPlus
    mobizt/Firebase ESP32 Client
    jrowberg/I2Cdevlib-MPU6050
board_build.filesystem = littlefs


monitor_speed = 115200
upload_speed  = 921600
